# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: iris_insee_utils

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with: 
        lfs: true 
    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
   # - name: Lint with flake8
   #   run: |
   #     # stop the build if there are Python syntax errors or undefined names
   #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
   #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
   #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Download and prepare data for tests
      run: |
        make install_library
        make download_and_initialize_data
    - name: Test with pytest
      run: |
        make launch_test
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false
